### PR TITLE
Update to 1.19

### PR DESCRIPTION
**Pull request by rdrpenguin04**
Hello! I'm new here; I just wanted to help update a mod for once instead of adding to the list of people complaining.

One thing is still blocking me: I'm not sure how to correctly install the plugin. When I use `rei`, it brings up a warning screen that seems impossible to bypass (including clicking Continue; the game hangs on my pack). When I use `rei-client`, the tab doesn't load in the first place. I'm guessing the answer is `rei-common`, but I don't know if that requires some other base class. I also don't know what Forge's requirements are.

Other than that though, it was a relatively easy port up to 1.19 as far as I can tell. Let me know if you have any questions or suggestions!

### CODE REVIEW

**Comment by rdrpenguin04** [comment]
Alright, should be good to go; just tested it.

**Comment by aaKugelblitz** [comment]
hey I tried building your fork and it looks like Minecraft isn't recognizing the mod when in the mods folder but still successfully starting the game. I don't have any experience with modding so its possible I did something wrong, just wanted to let you know.

**Comment by rdrpenguin04** [comment]
You may be building the mod wrong; building on Architectury is a slightly more convoluted process than normal Fabric or Forge; you need to run the `gradlew build`, but then you need to take the mod from `fabric/build/lib` or `forge/build/libs`, not `build/libs`. I hope this helps!

**Comment by aaKugelblitz** [comment]
hey thanks for the reply, that worked! :)

**Comment by rdrpenguin04** [comment]
Thank you! 😁

**Pull request merged**
